version: "3"
services:
    ocdb:
        container_name: ocdb
        image: mysql:5.7
        volumes:
                - ./db:/var/lib/mysql
        environment:
              - MYSQL_DATABASE=ocdb
              - MYSQL_ROOT_PASSWORD=P4ssw0rd!
        env_file: .env
        networks:
                - ocnet
    opencart:
        container_name: opencart
        image: citypay/opencart:latest
        ports:
                - 127.0.0.1:80:80
        environment:
               - CITYPAY_PLUGIN_VERSION= 1.1.0
        depends_on:
                - ocdb
        env_file: .env
        networks:
                - ocnet
        volumes:
          - ./src:/var/www/html/wp-content/plugins/citypay-paylink-woocommerce
networks:
    ocnet:
      driver: bridge